# Generated by Django 2.1.5 on 2021-07-15 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=30)),
                ('availability', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=11)),
                ('phone', models.IntegerField()),
                ('vehicle_type', models.CharField(max_length=20)),
                ('image', models.FileField(default='profile_pics/default.jpg', upload_to='profile_pics/')),
                ('description', models.TextField(max_length=100, null=True)),
                ('least_price', models.IntegerField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
