# Generated by Django 2.1.5 on 2021-07-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartmovers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default='movers_pics/default.jpg', upload_to='movers_pics/'),
        ),
    ]
