# Generated by Django 2.1.5 on 2021-07-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartmovers', '0002_auto_20210715_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], max_length=11),
        ),
    ]
