# Generated by Django 2.1.5 on 2021-07-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartmovers', '0003_auto_20210719_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='availability',
            field=models.CharField(choices=[('Available', 'Available'), ('Anavailable', 'Unavailable')], max_length=11),
        ),
    ]
