# Generated by Django 2.1.5 on 2021-07-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartmovers', '0007_auto_20210723_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
