# Generated by Django 2.1.5 on 2021-07-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartmovers', '0010_auto_20210726_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='movers_pics/'),
        ),
    ]
