# Generated by Django 2.1.5 on 2021-07-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartmovers', '0013_auto_20210727_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.CharField(choices=[('Very Dissatisfied', '1'), ('Dissatisfied', '2'), ('Fair', '3'), ('Satisfied', '4'), ('Very Satisfied', '5')], max_length=50, null=True),
        ),
    ]
