# Generated by Django 3.2.5 on 2021-07-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartmovers', '0015_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='movers/default.jpg', upload_to='movers_pics/'),
        ),
    ]
