# Generated by Django 3.2.5 on 2021-07-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartmovers', '0018_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.CharField(choices=[('1', '1-Very Dissatisfied'), ('2', '2-Dissatisfied'), ('3', '3-Fair'), ('4', '4-Satisfied'), ('5', '5-Very Satisfied')], max_length=50, null=True),
        ),
    ]
