# Generated by Django 3.2.5 on 2021-07-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartmovers', '0019_alter_rating_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='author',
            new_name='user',
        ),
    ]
