# Generated by Django 3.2.5 on 2021-07-30 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartmovers', '0020_rename_author_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postrating', to='smartmovers.post'),
        ),
    ]
