# Generated by Django 3.2.5 on 2021-08-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartmovers', '0023_alter_rating_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, '1-Very Dissatisfied'), (2, '2-Dissatisfied'), (3, '3-Fair'), (4, '4-Satisfied'), (5, '5-Very Satisfied')], max_length=50, null=True),
        ),
    ]
