# Generated by Django 3.2.5 on 2021-08-10 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smartmovers', '0024_auto_20210809_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
