# Generated by Django 3.2.5 on 2021-08-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartmovers', '0025_rating_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='posted',
            field=models.DateField(),
        ),
    ]
