# Generated by Django 3.2.5 on 2021-08-11 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smartmovers', '0026_alter_rating_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='posted',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
    ]
