# Generated by Django 3.2.5 on 2021-08-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartmovers', '0027_alter_rating_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='posted',
        ),
    ]
