# Generated by Django 3.2.5 on 2021-08-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartmovers', '0030_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default='movers_pics/default.jpg', upload_to='movers_pics/'),
        ),
    ]
